create or replace PROCEDURE INSERT_MOVIE_GENRE(p_id IN NUMBER, p_idGenre IN NUMBER) AS


BEGIN

  INSERT INTO MOVIE_GENRE VALUES(p_idGenre,p_id );

EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN PROC_LOG('insert_movie_genre: SQLCODE : ' || SQLCODE || ' SQLERRM : ' || SQLERRM);
  WHEN OTHERS THEN PROC_LOG('insert_movie_genre: ' || p_id || ' SQLCODE : ' || SQLCODE || ' SQLERRM : ' || SQLERRM);
END INSERT_MOVIE_GENRE;